[package]
name            = "stalin-binary-search"
version         = "0.0.1"
authors         = ["Miezhiko <Miezhiko@gmail.com>"]
edition         = "2021"
rust-version    = "1.56.0"

[lib]
doctest = false
